swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: 
    name: Nickolas Ruppenthal
    email: nick.ruppenthal@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:9999
basePath: /
tags:
  - name: product-resource
    description: Product Resource
paths:
  /products:
    get:
      tags:
        - product-resource
      summary: list
      operationId: listUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProdutoDto'
        '500':
          description: 500 Massege
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ExceptionResponse'
    post:
      tags:
        - product-resource
      summary: create
      operationId: createUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: pDto
          description: pDto
          required: true
          schema:
            $ref: '#/definitions/ProdutoDto'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/ProdutoDto'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: 500 Massage
          schema:
            $ref: '#/definitions/ExceptionResponse'
  /products/search:
    get:
      tags:
        - product-resource
      summary: search
      operationId: searchUsingGET
      produces:
        - '*/*'
      parameters:
        - name: max_price
          in: query
          description: max_price
          required: false
          type: number
          format: double
        - name: min_price
          in: query
          description: min_price
          required: false
          type: number
          format: double
        - name: name
          in: query
          description: name
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProdutoDto'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ExceptionResponse'      
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: 500 message
          schema:
            $ref: '#/definitions/ExceptionResponse'
  /products/{id}:
    get:
      tags:
        - product-resource
      summary: findById
      operationId: findByIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ProdutoDto'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: 500 Massege
          schema:
            $ref: '#/definitions/ExceptionResponse'
    put:
      tags:
        - product-resource
      summary: update
      operationId: updateUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
        - in: body
          name: pDto
          description: pDto
          required: true
          schema:
            $ref: '#/definitions/ProdutoDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ProdutoDto'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ExceptionResponse'      
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: 500 message
          schema:
            $ref: '#/definitions/ExceptionResponse'
    delete:
      tags:
        - product-resource
      summary: delete
      operationId: deleteUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DeleteDto'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ExceptionResponse'      
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ExceptionResponse'
        '500':
          description: 500 message
          schema:
            $ref: '#/definitions/ExceptionResponse'
definitions:
  DeleteDto:
    type: object
    properties:
      id:
        type: integer
        format: int32
      mensagem:
        type: string
    title: DeleteDto
  ProdutoDto:
    type: object
    properties:
      description:
        type: string
      id:
        type: integer
        format: int32
      name:
        type: string
      price:
        type: number
        format: double
    title: ProdutoDto
  ExceptionResponse:
    type: object
    properties:
      status_code:
        type: integer
        format: int64
      message:
        type: string
    title: ExceptionResponse   
